### ISSUE TITLE
Children & actors?

### ISSUE THREAD

**Issue by tomByrer** [shuvalov-mdb/xstate-cpp-generator#1]
Hi, thanks for expanding XState into C++!
Seems like you only handle a subset of XState's API, more closer to a [Finite State Machine](https://github.com/davidkpiano/xstate/tree/master/packages/xstate-fsm#xstatefsm)?

Is this by intention, or will you expand your program into the full StateChart API?

I do not program in C++, but I do intend to learn [V-lang](https://vlang.io/) sometime in the future, so it might be easier to import this lib or use as inspiration.

**Comment by shuvalov-mdb** [comment]
True. Yes, the goal is to have a *production stable* FSM generator with _necessary_ features. Xstate is for web development and it has a lot more than server-side C++ developers need. I will be very eager to fix bugs and improve stability issues if found in the features I already implemented. New features - let's discuss when there is a concrete project that needs them and perhaps I will ask for help to implement new features collaboratively.

**Comment by tomByrer** [comment]
Thanks!

(no need to keep this open; will open new issues as-needed)
